version: '2'
services:
    pkgserver:
        image: juliapackaging/pkgserver.jl
        user: $UID
        restart: unless-stopped
        expose:
            - 8000
        volumes:
            - ./cache:/app/cache
        environment:
            PKGSERVER_HOST: "0.0.0.0"
            PKGSERVER_PORT: "8000"
            PKGSERVER_STORAGESERVERS: "https://pkg.julialang.org"
        labels:
            # Tell watchtower to auto-update this guy
            com.centurylinklabs.watchtower.enable: true
    
    frontend:
        build:
            context: frontend
            args:
                FQDN: $FQDN
        restart: unless-stopped
        environment:
            CERTBOT_EMAIL: $CERTBOT_EMAIL
        ports:
            - 80:80/tcp
            - 443:443/tcp
        depends_on:
            - pkgserver
        volumes:
            - letsencrypt:/etc/letsencrypt
            - ./logs/nginx:/logs

    # Auto-reload docker containers when their images are updated
    watchtower:
        image: containrrr/watchtower
        volumes:
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --label-enable

volumes:
    letsencrypt:
