version: '2'
services:
    pkgserver:
        build:
            # We tell it the build context is `..` because we
            # actually want to copy the parent directory in so
            # that we can `Pkg.add()` it during the build
            context: ..
            dockerfile: deployment/pkgserver/Dockerfile

        restart: unless-stopped
        expose:
            - 8000
        environment:
            PKGSERVER_HOST: "0.0.0.0"
            PKGSERVER_PORT: "8000"
            PKGSERVER_STORAGESERVERS: "https://pkg.julialang.org"
        volumes:
            - cache:/app/cache

    webhook:
        image: staticfloat/docker-webhook
        volumes:
            # Mount this very repository into /code
            - ../:/code
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WEBHOOK_HOOKS_DIR: "/code/deployment/autoupdate"
            WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
            WEBHOOK_BRANCH_LIST: "${CONFIG_BRANCH}"
    
    frontend:
        build:
            context: frontend
            args:
                FQDN: $FQDN
        restart: unless-stopped
        environment:
            CERTBOT_EMAIL: $CERTBOT_EMAIL
        ports:
            - 80:80/tcp
            - 443:443/tcp
        depends_on:
            - pkgserver
            - webhook
volumes:
    cache:
